/**
 * Canonical data contracts for agor.
 *
 * Two contracts are the spine of the system:
 *  - {@link IVendorPlugin}  — the shape of a declarative YAML vendor manifest.
 *  - {@link IScrapedItem}   — the normalized internal item every component speaks.
 *
 * Everything else here is the supporting internal domain model (monitors,
 * price points, notifications, deal tags) shared across components.
 */

// ────────────────────────────────────────────────────────────────────────────
// Vendor plugin contract (YAML manifest shape)
// ────────────────────────────────────────────────────────────────────────────

export type PluginEngine = 'json-extractor' | 'dom-selector';

/**
 * How a manifest's pages are fetched:
 *   - `http`    — raw undici GET (default; works for vendors that ship listing
 *                 data in the initial HTML / flight payload),
 *   - `browser` — escalate to a real headless browser when the HTTP fetch hits a
 *                 recognised anti-bot hard block (for JS-gated / fingerprinted
 *                 vendors). Requires the optional browser dependency installed.
 */
export type FetchStrategy = 'http' | 'browser';

export interface IPluginMapping {
  /** Where the raw payload lives in the page (e.g. `script#__NEXT_DATA__`). */
  payload_locator: string;
  /** Dot/bracket path from the payload root to the item(s). */
  json_path: string;
  /** Map of IScrapedItem field name → path within a single item node. */
  fields: Record<string, string>;
  /**
   * Optional canonical-spec-name → path map, building {@link IScrapedItem.attributes}.
   * Paths resolve within a single item node (same dialect as `fields`). Use for
   * vendors with DEDICATED spec fields (e.g. a property's `areaInSquareMeters`).
   */
  attributes?: Record<string, string>;
  /**
   * Optional flexible spec extraction: explode a key/value array into the
   * attributes bag. Use for MULTI-CATEGORY vendors whose listings carry a generic
   * `params: [{key,value}]` array (a car, an apartment and a phone expose totally
   * different params), so a fixed key list would miss most of them.
   */
  attributes_from?: AttributesFrom;
}

/** Declarative explode of a key/value array into the attributes bag. */
export interface AttributesFrom {
  /** Path to the array of `{<key>, <value>}` records within an item node. */
  path: string;
  /** Field on each element used as the attribute NAME (prefer a human label). */
  key: string;
  /** Field on each element used as the attribute VALUE. */
  value: string;
}

export interface IPluginSearchMapping {
  payload_locator: string;
  /** Path from the payload root to the array of item nodes. */
  json_path_to_items: string;
  fields: Record<string, string>;
  /** Optional canonical-spec-name → path map (see {@link IPluginMapping.attributes}). */
  attributes?: Record<string, string>;
  /** Optional flexible key/value array explode (see {@link IPluginMapping.attributes_from}). */
  attributes_from?: AttributesFrom;
}

export interface IVendorPlugin {
  vendor: string;
  domain: string;
  engine: PluginEngine;
  /** Transport strategy; defaults to `http` when the manifest omits it. */
  fetch_strategy?: FetchStrategy;
  rate_limit_ms: number;
  search_mapping: IPluginSearchMapping;
  product_mapping: IPluginMapping;
}

// ────────────────────────────────────────────────────────────────────────────
// Normalized item contract
// ────────────────────────────────────────────────────────────────────────────

export interface IScrapedItem {
  /** Unique identifier generated by the vendor platform. */
  id: string;
  /** Raw clean listing name. */
  title: string;
  /** Clean numeric float. */
  price: number;
  /** Normalized ISO currency string (RON, EUR, …). */
  currency: string;
  /** Direct deep-link to the source listing. */
  url: string;
  /** Canonical preview image link. */
  imageUrl?: string;
  /** Isolates P2P sellers from B2C corporations. */
  isPrivateOwner: boolean;
  /** Parsed geographical / administrative region. */
  location?: string;
  /** Physical availability status. */
  inStock: boolean;
  /** Parsed seller phone, when available (powers the tel: deep link). */
  phone?: string;
  /** Parsed seller display name, when the vendor exposes one (powers block-seller). */
  sellerName?: string;
  /** Short listing description / teaser, when the vendor exposes one. */
  description?: string;
  /** When the listing was posted (epoch ms), parsed from the vendor's date. */
  postedAt?: number;
  /**
   * Structured listing specs as a flexible bag, e.g. `{ km, year, fuel }` for a
   * car or `{ area, rooms, floor }` for a property. The keys are canonical names
   * chosen by the manifest's `attributes` sub-map; values are display strings.
   */
  attributes?: Record<string, string>;
  /** Vendor that produced this item (set by the scraping engine). */
  vendor?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Internal domain model
// ────────────────────────────────────────────────────────────────────────────

export type MonitorType = 'search' | 'product';

/**
 * How a monitor came to exist:
 *   - 'user'    — the user explicitly added a search/product watch,
 *   - 'tracked' — auto-created by tapping "Track" on a browsed item.
 * Tracked monitors notify on ANY price change (not just drops) and are badged
 * in the watch list.
 */
export type MonitorOrigin = 'user' | 'tracked';

/** Seller-type visibility selection (Feature 7). */
export type SellerVisibility = 'private' | 'company' | 'both';

export interface FilterConfig {
  /** Which seller types the user wants to see. */
  sellerVisibility: SellerVisibility;
  /** Lowercased exclusion keywords (Feature 8). */
  exclusionKeywords: string[];
  /**
   * Lowercased required keywords (whitelist). When non-empty, a listing is kept
   * only if its title matches AT LEAST ONE keyword (word-boundary, like
   * exclusions). Absent/empty means "no requirement".
   */
  requiredKeywords?: string[];
  /** Lowercased seller display names to block (drops matching listings). */
  blockedSellers?: string[];
  /** Normalized (digits-only) seller phone numbers to block. */
  blockedPhones?: string[];
  /**
   * Target price (in the listing's own currency) for a product/tracked watch.
   * When the item's price first reaches at-or-below this, a `target_hit` alert
   * fires once (re-armed only if the price climbs back above the target).
   */
  targetPrice?: number;
  /**
   * Digest mode for a search watch: when set, new-listing alerts are NOT pinged
   * in real time but batched and delivered as a ranked daily/weekly summary
   * (best deals first, with market stats). Absent = real-time alerts.
   */
  digest?: 'daily' | 'weekly';
  /**
   * When true, a search watch emits an auto-generated weekly market report
   * (inventory trend, price movement, new-listing velocity, best deals).
   */
  weeklyReport?: boolean;
}

export interface Monitor {
  id: number;
  type: MonitorType;
  /** How the watch was created ('user' default, 'tracked' from browse). */
  origin: MonitorOrigin;
  /** Owning Telegram chat id. */
  chatId: number;
  /** Vendor that the target URL resolved to. */
  vendor: string;
  /** Scrubbed target URL (telemetry stripped, search params retained). */
  url: string;
  filters: FilterConfig;
  /** Base polling cadence in ms. */
  intervalMs: number;
  /** True while the scheduler holds this monitor on the fast (out-of-stock) tier. */
  fastTier: boolean;
  /** ms epoch of the next due poll. */
  nextDueAt: number;
  /** Consecutive unhealthy cycles (blocked / empty); drives failure surfacing. */
  consecutiveFailures: number;
  /** When true the scheduler skips this watch (paused, but config + history kept). */
  paused: boolean;
  /** Optional user-given name, shown in /list, /browse scope, and the edit card. */
  label?: string;
  /** Optional collection/folder this watch belongs to, for grouped /list + bulk ops. */
  collection?: string;
  createdAt: number;
}

export interface PricePoint {
  monitorId: number;
  /** Item id this price belongs to (search monitors track many items). */
  itemId: string;
  price: number;
  currency: string;
  /** ms epoch when observed. */
  observedAt: number;
}

// ────────────────────────────────────────────────────────────────────────────
// Analytics & notification
// ────────────────────────────────────────────────────────────────────────────

export type DealTag = 'great_deal' | 'fair_price' | 'overpriced';

export interface Benchmark {
  /** Statistical median across the target's active listings. */
  median: number;
  /** Number of listings the median was computed from. */
  sampleSize: number;
  /** False when sampleSize < BENCHMARK_MIN_SAMPLE. */
  confident: boolean;
}

/** An item enriched by the pipeline, ready to render. */
export interface EnrichedItem extends IScrapedItem {
  dealTag?: DealTag;
  benchmark?: Benchmark;
  /** Alternative vendor links merged in by cross-platform dedup. */
  alternativeSources?: Array<{ vendor: string; url: string }>;
}

export type NotificationKind =
  | 'new_listing'
  | 'price_drop'
  | 'back_in_stock'
  /** A cross-posted duplicate seen later: edit the original alert to add a source. */
  | 'cross_post'
  /** A watch is repeatedly failing (blocked / empty). */
  | 'watch_failing'
  /** A previously-failing watch is working again. */
  | 'watch_recovered'
  /** A tracked item's price moved in EITHER direction (tracked items only). */
  | 'price_change'
  /** A product/tracked item is gone (page 404'd or crossed the absent threshold). */
  | 'item_delisted'
  /** A search monitor's roll-up of listings that dropped off this cycle. */
  | 'listings_dropped'
  /** A delisted item reappeared within the memory window. */
  | 're_listed'
  /** A tracked item's price reached the user's target (threshold crossing). */
  | 'target_hit'
  /** A tracked item just crossed INTO a great deal vs comparable listings. */
  | 'became_deal'
  /** A batched daily/weekly summary of a digest-mode search watch's new listings. */
  | 'digest'
  /** An auto-generated weekly market report for a search watch. */
  | 'weekly_report';

export interface PriceDropInfo {
  previousPrice: number;
  currentPrice: number;
  /** previousPrice - currentPrice. */
  savings: number;
}

/** Payload for a tracked item's bidirectional price move. */
export interface PriceChangeInfo {
  previousPrice: number;
  currentPrice: number;
  /** 'down' when the price fell, 'up' when it rose. */
  direction: 'up' | 'down';
}

/** Payload for a target-price hit (price reached the user's threshold). */
export interface TargetHitInfo {
  targetPrice: number;
  currentPrice: number;
}

/** Payload for a became_deal alert (item just crossed into a great deal). */
export interface BecameDealInfo {
  /** Share of comparables priced below it (0..1). */
  percentile: number;
  /** Number of comparables. */
  n: number;
}

/** A category the fair-value model can value. */
export type ValuationCategory = 'car' | 'property';

/** Model-predicted fair value for a listing (v2). */
export interface FairValue {
  category: ValuationCategory;
  /** Predicted fair price (same currency as the listing). */
  fair: number;
  /** price − fair (negative = under fair). */
  delta: number;
  /** delta / fair (negative = under fair). */
  deltaPct: number;
  /**
   * How the estimate was reached: 'high'/'medium' = hedonic median of enough
   * adjusted comparables (level from comps, slopes from the model); 'low' = the
   * raw model prediction, with a level that may skew from tracking bias.
   */
  confidence?: 'high' | 'medium' | 'low';
}

/** Negotiation-relevant signals derived from a listing's age + price history. */
export interface MarketInsight {
  /** Whole days since the listing was posted (omitted when postedAt is unknown). */
  daysOnMarket?: number;
  /** Count of consecutive price decreases across the recorded history. */
  priceCuts: number;
  /** Lowest price ever observed (omitted when there is no history). */
  lowestPrice?: number;
}

/** Why an item is considered gone. */
export type DelistReason =
  /** A product page returned a client error (404/410). */
  | 'product_gone'
  /** A search-derived item was absent for the grace threshold of cycles. */
  | 'search_dropped';

/** Payload for an item_delisted notification (the gone item + why). */
export interface DelistInfo {
  reason: DelistReason;
  /** The last price observed before it went, when known. */
  lastSeenPrice?: number;
}

/** Payload for a search monitor's per-cycle de-listing roll-up. */
export interface DroppedSummary {
  monitorId: number;
  vendor: string;
  /** Total listings that dropped off this cycle. */
  count: number;
  /** Ids of the dropped items — the bot loads their snapshots to show a
   *  browse-style card (photo + specs) per gone listing. */
  itemIds: string[];
}

/** Identifies an already-sent Telegram message so it can be edited in place. */
export interface MessageRef {
  chatId: number;
  messageId: number;
}

/** Payload for watch_failing / watch_recovered notices (no listing item). */
export interface WatchHealth {
  monitorId: number;
  vendor: string;
  url: string;
  consecutiveFailures: number;
}

export interface Notification {
  kind: NotificationKind;
  chatId: number;
  /** Present for listing kinds (new_listing/price_drop/back_in_stock/cross_post/
   *  price_change/item_delisted/re_listed). */
  item?: EnrichedItem;
  /** Present only for price_drop notifications. */
  priceDrop?: PriceDropInfo;
  /** Present only for price_change notifications (tracked items, any direction). */
  priceChange?: PriceChangeInfo;
  /** Present only for target_hit notifications. */
  target?: TargetHitInfo;
  /** Present only for became_deal notifications. */
  becameDeal?: BecameDealInfo;
  /** Optional market insight (time-on-market, price cuts) for a product alert. */
  insight?: MarketInsight;
  /** Optional model-predicted fair value (on a new_listing alert). */
  fairValue?: FairValue;
  /** Present only for item_delisted notifications. */
  delist?: DelistInfo;
  /** Present only for listings_dropped (search de-listing roll-up). */
  dropped?: DroppedSummary;
  /** Present only for cross_post notifications: the original alert to edit. */
  messageRef?: MessageRef;
  /** Present only for watch_failing / watch_recovered notices. */
  health?: WatchHealth;
  /** Present only for digest notifications: the batched summary to render. */
  digest?: DigestSummary;
  /** Present only for weekly_report notifications. */
  report?: WeeklyReportData;
}

/** A single batched listing inside a digest summary. */
export interface DigestEntry {
  itemId: string;
  title: string;
  price: number;
  currency: string;
  url: string;
  /** Benchmark deal tag at enqueue time, if any. */
  dealTag?: DealTag;
  /** Fair-value delta fraction at enqueue time (negative = under), if computed. */
  deltaPct?: number;
}

/** The payload for a `digest` notification: a watch's batched new listings. */
export interface DigestSummary {
  vendor: string;
  /** 'daily' | 'weekly' — the window this digest covers. */
  period: 'daily' | 'weekly';
  /** The batched listings (unranked; the renderer ranks best-deals-first). */
  entries: DigestEntry[];
}

/** One "best deal" row in a weekly report. */
export interface ReportDeal {
  title: string;
  price: number;
  currency: string;
  url: string;
}

/** The payload for a `weekly_report` notification. */
export interface WeeklyReportData {
  vendor: string;
  /** Listings currently tracked (price-history reconstruction). */
  inventory: number;
  /** inventory − inventory a week ago (signed). */
  inventoryDelta: number;
  /** New listings first seen in the last 7 days. */
  newThisWeek: number;
  /** Pre-rendered, language-neutral price-trend badge ('' when no trend). */
  trendBadge: string;
  /** Cheapest current listings, best first. */
  bestDeals: ReportDeal[];
  /** Seasonal "best time to buy" month (1–12), when a pattern is detected. */
  seasonalMonth?: number;
  /** How far that month sits below the yearly mean, in percent. */
  seasonalBelowPct?: number;
}
