/**
 * Canonical data contracts for agor.
 *
 * Two contracts are the spine of the system:
 *  - {@link IVendorPlugin}  — the shape of a declarative YAML vendor manifest.
 *  - {@link IScrapedItem}   — the normalized internal item every component speaks.
 *
 * Everything else here is the supporting internal domain model (monitors,
 * price points, notifications, deal tags) shared across components.
 */

// ────────────────────────────────────────────────────────────────────────────
// Vendor plugin contract (YAML manifest shape)
// ────────────────────────────────────────────────────────────────────────────

export type PluginEngine = 'json-extractor' | 'dom-selector';

/**
 * How a manifest's pages are fetched:
 *   - `http`    — raw undici GET (default; works for vendors that ship listing
 *                 data in the initial HTML / flight payload),
 *   - `browser` — escalate to a real headless browser when the HTTP fetch hits a
 *                 recognised anti-bot hard block (for JS-gated / fingerprinted
 *                 vendors). Requires the optional browser dependency installed.
 */
export type FetchStrategy = 'http' | 'browser';

export interface IPluginMapping {
  /** Where the raw payload lives in the page (e.g. `script#__NEXT_DATA__`). */
  payload_locator: string;
  /** Dot/bracket path from the payload root to the item(s). */
  json_path: string;
  /** Map of IScrapedItem field name → path within a single item node. */
  fields: Record<string, string>;
}

export interface IPluginSearchMapping {
  payload_locator: string;
  /** Path from the payload root to the array of item nodes. */
  json_path_to_items: string;
  fields: Record<string, string>;
}

export interface IVendorPlugin {
  vendor: string;
  domain: string;
  engine: PluginEngine;
  /** Transport strategy; defaults to `http` when the manifest omits it. */
  fetch_strategy?: FetchStrategy;
  rate_limit_ms: number;
  search_mapping: IPluginSearchMapping;
  product_mapping: IPluginMapping;
}

// ────────────────────────────────────────────────────────────────────────────
// Normalized item contract
// ────────────────────────────────────────────────────────────────────────────

export interface IScrapedItem {
  /** Unique identifier generated by the vendor platform. */
  id: string;
  /** Raw clean listing name. */
  title: string;
  /** Clean numeric float. */
  price: number;
  /** Normalized ISO currency string (RON, EUR, …). */
  currency: string;
  /** Direct deep-link to the source listing. */
  url: string;
  /** Canonical preview image link. */
  imageUrl?: string;
  /** Isolates P2P sellers from B2C corporations. */
  isPrivateOwner: boolean;
  /** Parsed geographical / administrative region. */
  location?: string;
  /** Physical availability status. */
  inStock: boolean;
  /** Parsed seller phone, when available (powers the tel: deep link). */
  phone?: string;
  /** Vendor that produced this item (set by the scraping engine). */
  vendor?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Internal domain model
// ────────────────────────────────────────────────────────────────────────────

export type MonitorType = 'search' | 'product';

/** Seller-type visibility selection (Feature 7). */
export type SellerVisibility = 'private' | 'company' | 'both';

export interface FilterConfig {
  /** Which seller types the user wants to see. */
  sellerVisibility: SellerVisibility;
  /** Lowercased exclusion keywords (Feature 8). */
  exclusionKeywords: string[];
}

export interface Monitor {
  id: number;
  type: MonitorType;
  /** Owning Telegram chat id. */
  chatId: number;
  /** Vendor that the target URL resolved to. */
  vendor: string;
  /** Scrubbed target URL (telemetry stripped, search params retained). */
  url: string;
  filters: FilterConfig;
  /** Base polling cadence in ms. */
  intervalMs: number;
  /** True while the scheduler holds this monitor on the fast (out-of-stock) tier. */
  fastTier: boolean;
  /** ms epoch of the next due poll. */
  nextDueAt: number;
  /** Consecutive unhealthy cycles (blocked / empty); drives failure surfacing. */
  consecutiveFailures: number;
  createdAt: number;
}

export interface PricePoint {
  monitorId: number;
  /** Item id this price belongs to (search monitors track many items). */
  itemId: string;
  price: number;
  currency: string;
  /** ms epoch when observed. */
  observedAt: number;
}

// ────────────────────────────────────────────────────────────────────────────
// Analytics & notification
// ────────────────────────────────────────────────────────────────────────────

export type DealTag = 'great_deal' | 'fair_price' | 'overpriced';

export interface Benchmark {
  /** Statistical median across the target's active listings. */
  median: number;
  /** Number of listings the median was computed from. */
  sampleSize: number;
  /** False when sampleSize < BENCHMARK_MIN_SAMPLE. */
  confident: boolean;
}

/** An item enriched by the pipeline, ready to render. */
export interface EnrichedItem extends IScrapedItem {
  dealTag?: DealTag;
  benchmark?: Benchmark;
  /** Alternative vendor links merged in by cross-platform dedup. */
  alternativeSources?: Array<{ vendor: string; url: string }>;
}

export type NotificationKind =
  | 'new_listing'
  | 'price_drop'
  | 'back_in_stock'
  /** A cross-posted duplicate seen later: edit the original alert to add a source. */
  | 'cross_post'
  /** A watch is repeatedly failing (blocked / empty). */
  | 'watch_failing'
  /** A previously-failing watch is working again. */
  | 'watch_recovered';

export interface PriceDropInfo {
  previousPrice: number;
  currentPrice: number;
  /** previousPrice - currentPrice. */
  savings: number;
}

/** Identifies an already-sent Telegram message so it can be edited in place. */
export interface MessageRef {
  chatId: number;
  messageId: number;
}

/** Payload for watch_failing / watch_recovered notices (no listing item). */
export interface WatchHealth {
  monitorId: number;
  vendor: string;
  url: string;
  consecutiveFailures: number;
}

export interface Notification {
  kind: NotificationKind;
  chatId: number;
  /** Present for listing kinds (new_listing/price_drop/back_in_stock/cross_post). */
  item?: EnrichedItem;
  /** Present only for price_drop notifications. */
  priceDrop?: PriceDropInfo;
  /** Present only for cross_post notifications: the original alert to edit. */
  messageRef?: MessageRef;
  /** Present only for watch_failing / watch_recovered notices. */
  health?: WatchHealth;
}
